'use client';

import { ReactNode, useCallback, useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { fetchCurrentUser } from '@/services/auth.service';

/**
 * One mechanism for every printable document in the app.
 *
 * A printed document is its OWN document, not a screenshot of the app. The sheet is portalled
 * into a dedicated `#print-root` at the end of <body>, and while a print is in flight the
 * stylesheet hides every other top-level node — so the paper carries the document alone, and
 * the browser supplies page numbers and the date in the page margins.
 *
 * Two rules here are load-bearing, both learned the hard way by the depreciation schedule
 * (see the comments beside its CSS in globals.scss):
 *
 *  1. The body-child hiding rule is SCOPED to a class that exists only while printing. An
 *     unscoped rule hid every body child on every route and printed the rest of the app blank.
 *  2. `@page` is NAMED. The app-wide print block declares `@page { margin: … !important }`, so
 *     an anonymous override re-margins every other printable view and a non-important rule
 *     simply loses.
 *
 * The sheet is mounted CONTINUOUSLY once armed rather than on click: mounting it inside the
 * click handler races the browser's document snapshot, and the loser is a blank page.
 */

interface IPrintIdentity {
  /** For the letterhead. Never invented — the JWT carries an id, not a name. */
  companyName: string;
  /** For the provenance line: who produced this piece of paper. */
  userName: string;
}

/**
 * Company + user for the letterhead and the "generated by" line. `/AppUsers/me` is
 * authenticated with no permission gate, and the result is cached module-wide because every
 * sheet on every page wants exactly the same two strings.
 */
let identityCache: IPrintIdentity | null = null;
let identityInFlight: Promise<IPrintIdentity> | null = null;

const loadIdentity = (): Promise<IPrintIdentity> => {
  if (identityCache) return Promise.resolve(identityCache);
  if (!identityInFlight)
    identityInFlight = fetchCurrentUser()
      .then((response) => {
        identityCache = {
          companyName: response?.data?.companyName?.trim() || '',
          userName:
            response?.data?.fullName?.trim() || response?.data?.username?.trim() || '',
        };
        return identityCache;
      })
      .catch(() => ({ companyName: '', userName: '' }))
      .finally(() => {
        identityInFlight = null;
      });
  return identityInFlight;
};

export const usePrintIdentity = (): IPrintIdentity => {
  const [identity, setIdentity] = useState<IPrintIdentity>(
    identityCache ?? { companyName: '', userName: '' }
  );

  useEffect(() => {
    let live = true;
    loadIdentity().then((value) => {
      if (live) setIdentity(value);
    });
    return () => {
      live = false;
    };
  }, []);

  return identity;
};

/**
 * Arms a print sheet and returns `print()`.
 *
 * `armed` gates the whole mechanism: pass false (e.g. while the document's data is still
 * loading) and nothing is mounted and no body class is set, so an unrelated print of the page
 * behaves exactly as it did before.
 */
export const usePrintSheet = (armed = true) => {
  useEffect(() => {
    if (!armed) return;
    document.body.classList.add('printing');
    // Cleanup on unmount AND on disarm — a body class that outlives its sheet blanks the
    // next thing the operator prints.
    return () => document.body.classList.remove('printing');
  }, [armed]);

  const print = useCallback(() => {
    if (!armed) return;
    window.print();
  }, [armed]);

  /**
   * The document, shown on screen as a PREVIEW with its own Print button.
   *
   * It used to print the instant it armed. That is what produced blank paper: the sheet was
   * `display: none` at every size except `@media print`, so nothing was ever visible to check,
   * and window.print() fired on the same tick the portal mounted — whichever won the race
   * decided whether the page had content. Worse, a blank result was indistinguishable from a
   * printer problem, because there was nothing on screen to compare against.
   *
   * Now the sheet is rendered visibly, at paper proportions, and the operator presses Print
   * when they can see what they are about to sign. That removes the race completely (the
   * document has been on screen for however long they looked at it) and makes a genuinely
   * empty document obvious instead of mysterious.
   */
  const PrintSheet = useCallback(
    ({
      children,
      landscape,
      title = 'Print preview',
      onClose,
    }: {
      children: ReactNode;
      /** Wide tables (a count sheet, a register listing) that do not fit portrait. */
      landscape?: boolean;
      /** Shown in the preview toolbar — names the document being previewed. */
      title?: string;
      /** Disarms the sheet. Wired to Close, the backdrop and Escape. */
      onClose?: () => void;
    }) => {
      if (!armed || typeof document === 'undefined') return null;
      return createPortal(
        <div
          id="print-root"
          className="print-preview"
          role="dialog"
          aria-modal="true"
          aria-label={title}
          onClick={(e) => {
            if (e.target === e.currentTarget) onClose?.();
          }}
        >
          {/* Screen-only chrome — hidden by @media print so it never reaches paper. */}
          <div className="print-preview__chrome">
            <span className="print-preview__title">{title}</span>
            <span className="print-preview__actions">
              <button
                type="button"
                onClick={print}
                className="rounded-full bg-primarycolor px-4 py-1.5 text-sm font-medium text-white hover:brightness-95"
              >
                <i className="icon icon-print mr-1.5 text-xs" />
                Print
              </button>
              <button
                type="button"
                onClick={onClose}
                className="rounded-full border border-gray-300 bg-white px-4 py-1.5 text-sm font-medium text-secondaryColor hover:bg-gray-50"
              >
                Close
              </button>
            </span>
          </div>

          <div
            className={`print-sheet${landscape ? ' print-sheet--landscape' : ''}`}
          >
            {children}
          </div>
        </div>,
        document.body
      );
    },
    [armed, print]
  );

  return { print, PrintSheet };
};

export default usePrintSheet;
