'use client';

import { ReactNode, useCallback, useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { fetchCurrentUser } from '@/services/auth.service';

/**
 * One mechanism for every printable document in the app.
 *
 * A printed document is its OWN document, not a screenshot of the app. The sheet is portalled
 * into a dedicated `#print-root` at the end of <body>, and while a print is in flight the
 * stylesheet hides every other top-level node — so the paper carries the document alone, and
 * the browser supplies page numbers and the date in the page margins.
 *
 * Two rules here are load-bearing, both learned the hard way by the depreciation schedule
 * (see the comments beside its CSS in globals.scss):
 *
 *  1. The body-child hiding rule is SCOPED to a class that exists only while printing. An
 *     unscoped rule hid every body child on every route and printed the rest of the app blank.
 *  2. `@page` is NAMED. The app-wide print block declares `@page { margin: … !important }`, so
 *     an anonymous override re-margins every other printable view and a non-important rule
 *     simply loses.
 *
 * The sheet is mounted CONTINUOUSLY once armed rather than on click: mounting it inside the
 * click handler races the browser's document snapshot, and the loser is a blank page.
 */

interface IPrintIdentity {
  /** For the letterhead. Never invented — the JWT carries an id, not a name. */
  companyName: string;
  /** For the provenance line: who produced this piece of paper. */
  userName: string;
}

/**
 * Company + user for the letterhead and the "generated by" line. `/AppUsers/me` is
 * authenticated with no permission gate, and the result is cached module-wide because every
 * sheet on every page wants exactly the same two strings.
 */
let identityCache: IPrintIdentity | null = null;
let identityInFlight: Promise<IPrintIdentity> | null = null;

const loadIdentity = (): Promise<IPrintIdentity> => {
  if (identityCache) return Promise.resolve(identityCache);
  if (!identityInFlight)
    identityInFlight = fetchCurrentUser()
      .then((response) => {
        identityCache = {
          companyName: response?.data?.companyName?.trim() || '',
          userName:
            response?.data?.fullName?.trim() || response?.data?.username?.trim() || '',
        };
        return identityCache;
      })
      .catch(() => ({ companyName: '', userName: '' }))
      .finally(() => {
        identityInFlight = null;
      });
  return identityInFlight;
};

export const usePrintIdentity = (): IPrintIdentity => {
  const [identity, setIdentity] = useState<IPrintIdentity>(
    identityCache ?? { companyName: '', userName: '' }
  );

  useEffect(() => {
    let live = true;
    loadIdentity().then((value) => {
      if (live) setIdentity(value);
    });
    return () => {
      live = false;
    };
  }, []);

  return identity;
};

/**
 * Arms a print sheet and returns `print()`.
 *
 * `armed` gates the whole mechanism: pass false (e.g. while the document's data is still
 * loading) and nothing is mounted and no body class is set, so an unrelated print of the page
 * behaves exactly as it did before.
 */
export const usePrintSheet = (armed = true) => {
  useEffect(() => {
    if (!armed) return;
    document.body.classList.add('printing');
    // Cleanup on unmount AND on disarm — a body class that outlives its sheet blanks the
    // next thing the operator prints.
    return () => document.body.classList.remove('printing');
  }, [armed]);

  // A document's data usually lands in two stages — the row first, then an enriching fetch —
  // and the effect that triggers the print re-runs on each. Without this the print dialog
  // opens twice for one click. Reset when the sheet disarms, so the next document prints.
  const printed = useRef(false);
  useEffect(() => {
    if (!armed) printed.current = false;
  }, [armed]);

  const print = useCallback(() => {
    if (!armed || printed.current) return;
    printed.current = true;
    window.print();
  }, [armed]);

  /** Wraps the document and portals it. Render it unconditionally; CSS decides visibility. */
  const PrintSheet = useCallback(
    ({
      children,
      landscape,
    }: {
      children: ReactNode;
      /** Wide tables (a count sheet, a register listing) that do not fit portrait. */
      landscape?: boolean;
    }) => {
      if (!armed || typeof document === 'undefined') return null;
      return createPortal(
        <div
          id="print-root"
          className={`print-sheet${landscape ? ' print-sheet--landscape' : ''}`}
        >
          {children}
        </div>,
        document.body
      );
    },
    [armed]
  );

  return { print, PrintSheet };
};

export default usePrintSheet;
